version: '3.4'

volumes:
  mysql-data:
  app-cache:

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=roottestpasswd
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testpasswd
      - TZ=Europe/Paris
    ports:
      - "33068:3306"

  app:
    build: ./symfony
    volumes:
      - ./:/var/www/html
      - app-cache:/var/www/html/var/cache
      - /var/www/.composer
    depends_on:
      - db
